import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { build as esbuild } from "esbuild";

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED_DIR = path.join(ROOT_DIR, "mcp", "generated");
const WEB_DIST = path.join(ROOT_DIR, "web", "dist");
const CHECK_ONLY = process.argv.includes("--check");
const temporaryRoot = await mkdtemp(path.join(tmpdir(), "xhs-simulator-build-"));

const names = {
  widget: "xhs-widget.html",
  server: "xhs-mcp.mjs",
  manifest: "release-manifest.json",
};

try {
  const widget = await inlineWidget();
  const serverPath = path.join(temporaryRoot, names.server);
  await esbuild({
    entryPoints: [path.join(ROOT_DIR, "mcp", "server.mjs")],
    outfile: serverPath,
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    minify: true,
    legalComments: "eof",
    banner: {
      js: 'import { createRequire as __createRequire } from "node:module"; const require = __createRequire(import.meta.url);',
    },
    logLevel: "warning",
  });
  const server = await readFile(serverPath);
  const packageJson = JSON.parse(await readFile(path.join(ROOT_DIR, "package.json"), "utf8"));
  const artifacts = new Map([
    [names.widget, Buffer.from(widget)],
    [names.server, server],
  ]);
  artifacts.set(
    names.manifest,
    Buffer.from(`${JSON.stringify({
      version: packageJson.version,
      generatedBy: "scripts/build-plugin.mjs",
      artifacts: Object.fromEntries(
        [...artifacts].map(([name, contents]) => [name, sha256(contents)]),
      ),
    }, null, 2)}\n`),
  );

  if (CHECK_ONLY) {
    for (const [name, expected] of artifacts) {
      const actual = await readFile(path.join(GENERATED_DIR, name));
      if (!actual.equals(expected)) throw new Error(`构建产物已过期：${name}`);
    }
    console.log("OK: plugin artifacts are current.");
  } else {
    await mkdir(GENERATED_DIR, { recursive: true });
    for (const [name, contents] of artifacts) {
      await writeFile(path.join(GENERATED_DIR, name), contents);
    }
    console.log(`Built ${artifacts.size} plugin artifacts.`);
  }
} finally {
  await rm(temporaryRoot, { recursive: true, force: true });
}

async function inlineWidget() {
  let html = await readFile(path.join(WEB_DIST, "index.html"), "utf8");
  const consumed = new Set();
  const scripts = [];

  html = await replaceAsync(
    html,
    /<link\s+rel="stylesheet"[^>]+href="([^"]+)"[^>]*>/g,
    async (_match, href) => {
      const css = await readAsset(href, consumed);
      return `<style>\n${css.replaceAll("</style", "<\\/style")}\n</style>`;
    },
  );
  html = await replaceAsync(
    html,
    /<script\s+type="module"[^>]+src="([^"]+)"[^>]*><\/script>/g,
    async (_match, src) => {
      const js = await readAsset(src, consumed);
      scripts.push(`<script>\n(() => {\n${js.replaceAll("</script", "<\\/script")}\n})();\n</script>`);
      return "";
    },
  );
  html = html.replace("</body>", `${scripts.join("\n")}\n</body>`);

  if (/\b(?:src|href)="[^"]*\/assets\//i.test(html)) {
    throw new Error("Widget 仍引用外部构建资源。");
  }
  const assetsDir = path.join(WEB_DIST, "assets");
  if (existsSync(assetsDir)) {
    const leftovers = (await readdir(assetsDir)).filter((name) => !consumed.has(`assets/${name}`));
    if (leftovers.length) throw new Error(`Widget 存在未内联资源：${leftovers.join(", ")}`);
  }
  return `<!-- Generated by scripts/build-plugin.mjs. -->\n${html}`;
}

async function readAsset(reference, consumed) {
  const relative = reference.replace(/^\.\//, "").replace(/^\//, "");
  if (relative.includes("..")) throw new Error(`非法构建资源路径：${reference}`);
  consumed.add(relative);
  return readFile(path.join(WEB_DIST, relative), "utf8");
}

async function replaceAsync(source, regex, replacer) {
  const matches = [...source.matchAll(regex)];
  let result = source;
  for (let index = matches.length - 1; index >= 0; index -= 1) {
    const match = matches[index];
    const replacement = await replacer(...match);
    result = `${result.slice(0, match.index)}${replacement}${result.slice(match.index + match[0].length)}`;
  }
  return result;
}

function sha256(contents) {
  return createHash("sha256").update(contents).digest("hex");
}
